1. Given an array of intervals where intervals[i] = [starti, endi], merge all overlapping intervals,
and return an array of the non-overlapping intervals that cover all the intervals in the input (25
points).

In [ ]:
import numpy as np

In [2]:
intervals_one = np.array([[1, 3], [2, 6], [8, 10], [15, 18]])
intervals_two = np.array([[1, 4], [4, 5]])
intervals_three = np.array([[1, 3], [2, 6], [8, 10], [15, 18], [16, 19], [18, 45]])

In [3]:
def overlapping_remover(intervals):
    overlapping = True
    i = 0
    while overlapping:
        overlapping = False
        while i < intervals.shape[0]-1:
            compare_one = intervals[i]
            compare_two = intervals[i+1]
            if compare_one[1] >= compare_two[0]:
                merged_array = np.array([[compare_one[0], compare_two[1]]])
                intervals = np.delete(intervals, i, 0)
                intervals = np.delete(intervals, i, 0)
                intervals = np.insert(intervals, i, merged_array, axis=0)
                overlapping = True
                i = 0
            i += 1
    return intervals

In [4]:
print(overlapping_remover(intervals_one))

[[ 1  6]
 [ 8 10]
 [15 18]]


In [6]:
print(overlapping_remover(intervals_two))

[[1 5]]


In [7]:
print(overlapping_remover(intervals_three))

[[ 1  6]
 [ 8 10]
 [15 45]]


2. Implement computing determinant for any N by N (N ≤ 10) square matrix without using existing
libraries for computing determinant such as numpy.linalg.det() (25 points).


In [14]:
from copy import deepcopy

def miner_matrix(original_matrix, row, column):
    miner_matrix = deepcopy(original_matrix)
    miner_matrix.remove(original_matrix[row])
    
    for i in range(len(miner_matrix)):
        miner_matrix[i].remove(miner_matrix[i][column])
    return miner_matrix

def determinant(matrix):
    num_rows = len(matrix)
    answer = 0
    num_columns = num_rows
    
    if len(matrix) == 2:
        two_by_two = matrix[0][0] * matrix[1][1] - matrix[1][0] * matrix[0][1]
        return two_by_two
    else :
        for j in range(num_columns):
            cofactor = (-1) ** (0+j) * matrix[0][j] * determinant(miner_matrix(matrix, 0, j))
            answer += cofactor
        return answer

In [17]:
#Generate matrix
matrix = np.random.randint(25, size=(4, 4))
print(matrix)

[[24 15 15 19]
 [18 20 23  1]
 [ 1  4  6 24]
 [21 14  2 11]]


In [18]:
#Check the calculated matrix is valid

matrix = matrix.tolist()
print(determinant(matrix))
print(np.linalg.det(matrix))

72387
72387.00000000006


3. (Scikit-learn and OpenCV) As a mini project, you will train Support Vector Machine classifier
with SIFT features for MNIST digit dataset, i.e., multi-class classification. (50 points)
MNIST dataset can be downloaded by using the following commands:

In [29]:
#Load MNIST
from keras.datasets import mnist
import cv2

(x_train, y_train), (x_test, y_test) = mnist.load_data()

In [41]:
sift = cv2.SIFT_create()
SIFT_train = []
for i in range(len(x_train)):
    sample_image = cv2.cvtColor(x_train[i], cv2.COLOR_GRAY2BGR)
    keypoints, descriptors = sift.detectAndCompute(sample_image, None)